-- Seed real material catalog from the client QuickBooks item list (ITEM LIST 2.xlsx).
-- Imports Inventory Part rows only: 188 materials (28 raw, 138 packaging, 22 consumable).
-- This intentionally does not create received lots, stock quantities, QA records, or fake demo data.

insert into public.materials (
  id,
  name,
  type,
  unit,
  supplier,
  low_stock_threshold,
  is_active
)
values
  ('BASE-001', '10kg Base, (700pc/skid plain) Jokey', 'packaging', 'each', 'IPL North America Inc.', null, true),
  ('BASE-002', '10kg Base, (600pc/skid plain) IPL', 'packaging', 'each', 'IPL North America Inc.', null, true),
  ('BASE-003', '12kg Base, (700pc/skid plain) Jokey', 'packaging', 'each', 'IPL North America Inc.', null, true),
  ('BASE-004', '16kg Base, (124pc/skid plain) IPL', 'packaging', 'each', 'IPL North America Inc.', null, true),
  ('BOTTLE-001', 'Ayran/Lassi bottles white 475ml', 'packaging', 'each', 'Silgan Plastics Canada Inc.', null, true),
  ('BOTTLE-002', 'Mango Lassi Bottle 1L', 'packaging', 'each', null, null, true),
  ('CAPS-001B', 'Ayran/Lassi Caps 475ml (BLUE)', 'packaging', 'each', 'Silgan Plastics Canada Inc.', null, true),
  ('CAPS-001G', 'AyranLassi Caps Plain 475ml (Green)', 'packaging', 'each', 'Silgan Plastics Canada Inc.', null, true),
  ('CAPS-001R', 'AyranLassi Caps Plain 475ml (Red)', 'packaging', 'each', null, null, true),
  ('CAPS-002', 'White Caps', 'packaging', 'each', null, null, true),
  ('CASE-001', 'Ayran/Lassi  Case', 'packaging', 'each', 'Staples Professional', null, true),
  ('CASE-002', 'Fruit Yogurt 170gm Case', 'packaging', 'each', 'Staples Professional', null, true),
  ('CASE-002A', 'Fruit Yogurt 170gm Case Insert', 'packaging', 'each', 'Staples Professional', null, true),
  ('CASE-003', 'Ghee 400gm Case', 'packaging', 'each', 'Staples Professional', null, true),
  ('CASE-004', 'Ghee 800gm Case (375pc/Skid)', 'packaging', 'each', 'Staples Professional', null, true),
  ('CASE-005', 'Ghee 1.6Kg Case', 'packaging', 'each', 'Staples Professional', null, true),
  ('CASE-006 (1)', 'Regular Paneer Case for 300g', 'packaging', 'each', 'Staples Professional', null, true),
  ('CASE-006 (2)', 'Malai Paneer Case for 300g', 'packaging', 'each', 'CP Packaging Coprp', null, true),
  ('CASE-006 (3)', 'Plain Paneer Case for 300g', 'packaging', 'each', 'CP Packaging Coprp', null, true),
  ('CASE-006 (4)', 'Apna Paneer Case for 300g', 'packaging', 'each', 'CP Packaging Coprp', null, true),
  ('CASE-007', 'Paneer case for 1.6kg', 'packaging', 'each', 'Staples Professional', null, true),
  ('CASE-007 (1)', 'Malai Paneer case for 1.6kg', 'packaging', 'each', 'IPL Plastic Inc.', null, true),
  ('CASE-007 (2)', 'Apna Paneer case for 1.6kg', 'packaging', 'each', 'CP Packaging Coprp', null, true),
  ('CASE-007 (3)', 'Plain Paneer case for 1.6kg', 'packaging', 'each', 'CP Packaging Coprp', null, true),
  ('CHEM-001', 'Activ', 'consumable', 'each', 'Sani Marc', null, true),
  ('CHEM-002', 'Alco Spray', 'consumable', 'each', 'Sani Marc', null, true),
  ('CHEM-003', 'Benefit', 'consumable', 'Pail', 'Diversey Canada Inc', null, true),
  ('CHEM-004', 'Carbo Blasst', 'consumable', 'each', 'Sani Marc', null, true),
  ('CHEM-005', 'Chloragel', 'consumable', 'each', 'Sani Marc', null, true),
  ('CHEM-006', 'Divosan Plus', 'consumable', 'each', 'Diversey Canada Inc', null, true),
  ('CHEM-007', 'Divosan Q400', 'consumable', 'each', 'Diversey Canada Inc', null, true),
  ('CHEM-008', 'Enduroplus', 'consumable', 'each', 'Diversey Canada Inc', null, true),
  ('CHEM-009', 'Enviro Acid', 'consumable', 'each', 'Sani Marc', null, true),
  ('CHEM-010', 'Germachlor Ultra', 'consumable', 'each', 'Sani Marc', null, true),
  ('CHEM-011', 'Non- Stick', 'consumable', 'each', 'Diversey Canada Inc', null, true),
  ('CHEM-012', 'Pascal', 'consumable', 'each', 'Diversey Canada Inc', null, true),
  ('CHEM-013', 'Soft care', 'consumable', 'each', 'Diversey Canada Inc', null, true),
  ('CHEM-014', 'SU 393', 'consumable', 'each', 'Diversey Canada Inc', null, true),
  ('CULTURE-001', 'ABY 3', 'raw', 'each', 'Fromagex', null, true),
  ('CULTURE-002', 'CHN-22', 'raw', 'each', 'Fromagex', null, true),
  ('CULTURE-003', 'Exact Dahi -2', 'raw', 'each', 'Fromagex', null, true),
  ('CULTURE-004', 'FLORA DANICA', 'raw', 'each', 'Fromagex', null, true),
  ('CULTURE-005', 'Fresh Q 4', 'raw', 'each', 'Fromagex', null, true),
  ('CULTURE-006', 'R-704', 'raw', 'each', 'Fromagex', null, true),
  ('CULTURE-007', 'YC- 381', 'raw', 'each', 'Fromagex', null, true),
  ('CULTURE-008', 'YC-X11', 'raw', 'each', 'Fromagex', null, true),
  ('CULTURE-009', 'Yo Flex Mild 1', 'raw', 'each', 'Fromagex', null, true),
  ('CUPS-001', '2% Probiotic Cups 750gm (576pc/box) IPL', 'packaging', 'each', 'IPL', null, true),
  ('CUPS-001P', '2% Probiotic Cups 750gm Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('CUPS-002', '2% Dahi Cups 750gm IPL', 'packaging', 'each', 'IPL', null, true),
  ('CUPS-003', '3.2% Dahi Cups 750gm, (576pc/box) IPL', 'packaging', 'each', 'IPL', null, true),
  ('CUPS-004', '500gm Plain Cups,630pc/box Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('CUPS-004 (1)', '500gm Plain Cups,630pc/box IPL', 'packaging', 'each', 'IPL Plastic Inc.', null, true),
  ('CUPS-005', '750gm Plain Cups, 630pc/box Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('CUPS-005 (1)', '750gm Plain Cups, 630pc/box IPL', 'packaging', 'each', 'IPL Plastic Inc.', null, true),
  ('CUPS-006', 'Mango Cups 170gm', 'packaging', 'each', 'Hong Kong Huasheng Holdings Limited', null, true),
  ('CUPS-007', 'Pineapple Cups 170gm', 'packaging', 'each', 'Hong Kong Huasheng Holdings Limited', null, true),
  ('CUPS-008', 'Strawberry Cups 170gm', 'packaging', 'each', 'Hong Kong Huasheng Holdings Limited', null, true),
  ('CUPS-009', 'Blueberry Cups 170gm', 'packaging', 'each', 'Hong Kong Huasheng Holdings Limited', null, true),
  ('CUPS-011', '6% Balkan Cups 750gm, (576pc/box) IPL', 'packaging', 'each', 'IPL', null, true),
  ('CUPS-012', 'Plain Khoa / Makhani  Container Cups Plastipak JOB 1.1', 'packaging', 'each', 'Plastipak', null, true),
  ('CUPS-013', 'Raspberry Cups 170gm', 'packaging', 'each', 'Hong Kong Huasheng Holdings Limited', null, true),
  ('CUPS-014', 'Red Cherry Cups 170gm', 'packaging', 'each', 'Hong Kong Huasheng Holdings Limited', null, true),
  ('ENZY-001', 'Microbial Enzyme', 'raw', 'each', 'Fromagex', null, true),
  ('FILM-001', 'Sealing Films 750gm 6" wide', 'packaging', 'each', 'Packall Packaging Inc.', null, true),
  ('FILM-002', 'Sealing Films 750gm 24" wide', 'packaging', 'ft', 'Packall Packaging Inc.', null, true),
  ('FILM-003', 'Sealing Bottom Film, Transparent 5mm', 'packaging', 'ft', 'Packall Packaging Inc.', null, true),
  ('FILM-004', 'Sealing Top Film Transparent 3.5mm', 'packaging', 'ft', 'Packall Packaging Inc.', null, true),
  ('FILM-005', 'Sealing Top Film Printed Modhani 300gm Malai Paneer', 'packaging', 'ft', 'Packall Packaging Inc.', null, true),
  ('FILM-006', 'Sealing Top Film Printed Modhani 1.6KG Malai Paneer', 'packaging', 'ft', 'Packall Packaging Inc.', null, true),
  ('FOIL-001', 'Mango Cups Sealing Foil', 'packaging', 'each', null, null, true),
  ('FOIL-002', 'Pineapple Cups Sealing Foil', 'packaging', 'each', null, null, true),
  ('FOIL-003', 'Strawberry Cups Sealing Foil', 'packaging', 'each', null, null, true),
  ('FOIL-004', 'Blueberry Cups Sealing Foil', 'packaging', 'each', null, null, true),
  ('FOIL-005', 'Raspberry Cups Sealing Foil', 'packaging', 'each', null, null, true),
  ('FOIL-006', 'Red Cherry Cups Sealing Foil', 'packaging', 'each', null, null, true),
  ('FRUIT-001', 'Frozen Mango', 'raw', 'lb', 'Miller & Smith', null, true),
  ('FRUIT-002', 'Frozen Pineapple', 'raw', 'lb', 'Miller & Smith', null, true),
  ('FRUIT-003', 'Frozen Strawberry', 'raw', 'lb', 'Miller & Smith', null, true),
  ('FRUIT-004', 'Frozen Blueberry', 'raw', 'lb', 'Miller & Smith', null, true),
  ('FRUIT-005', 'Frozen Raspberry', 'raw', 'lb', 'Miller & Smith', null, true),
  ('FRUIT-006', 'Frozen Redcherry', 'raw', 'lb', 'Miller & Smith', null, true),
  ('ING-001', 'Calcium Chloride', 'raw', 'kg', 'Brenntag Canada', null, true),
  ('ING-002', 'Cream 20 Liter Bag', 'raw', 'L', null, null, true),
  ('ING-003', 'Dairy Tex Sour Cream', 'raw', 'kg', 'Caldic Canada Inc.', null, true),
  ('ING-004', 'Pectin', 'raw', 'kg', 'Caldic Canada Inc.', null, true),
  ('ING-005', 'WAIU Butter', 'raw', 'kg', 'Lactalis Canada', null, true),
  ('ING-006', 'Citric Acid', 'raw', 'kg', 'Brenntag Canada', null, true),
  ('ING-007', 'Starch /  Ingredion', 'raw', 'kg', 'Caldic Canada Inc.', null, true),
  ('JARS-001', '400 gm Ghee Jars, 1800pc/skid', 'packaging', 'each', 'Silgan Plastics Canada Inc.', null, true),
  ('JARS-002', '800 gm Ghee Jars, 980pc/sid', 'packaging', 'each', 'Silgan Plastics Canada Inc.', null, true),
  ('JARS-003', '1.6 kg Ghee Jars', 'packaging', 'each', 'Poly Blow Moulding Inc', null, true),
  ('LABEL-001', 'Ghee, 400gm Label Product of New zealand', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-002', 'Ghee, 800gm Label Product of New zealand', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-003', 'Ghee, 1.6 kg Label Product of New zealand', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-004', 'Ghee, 3 kg Label front Product of New zealand', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-005', 'Ghee, 3 kg Label  back Product of New zealand', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-006', 'Ghee, 10 kg Label Front Product of New zealand', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-007', 'Ghee, 10 kg Label Back Product of New zealand', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-008', 'Case Label Pure Desi Ghee,400 gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-009', 'Case Label Pure Desi Ghee, 800 gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-010', 'Case Label Pure Desi Ghee, 1.6 kg', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-011', 'Case Label Pure Desi Ghee, 3 kg', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-012', 'Case Label Pure Desi Ghee, 10 KG', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-013 (1)', 'Sour Cream 250gm Labels', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-013 (2)', 'Sour Cream 5kg labels', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-013 (3)', 'Sour Cream 10 Kg Labels', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-014', 'Paneer Label 300gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-015', 'Malai Paneer  Label 300gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-016', 'Organic Paneer Label 300 gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-017', 'Apna Paneer Label 300gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-018', 'Paneer Label 1.6Kg', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-019', 'Malai Paneer Label 1.6Kg', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-020', 'Apna Paneer Label 1.6Kg', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-021', 'Khoya 1Kg Label Front', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-022', 'Khoya 1Kg Label Back', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-023', 'Case Label Mint Ayran', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-024', 'Case Label PLAIN Ayran', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-025', 'Mint Ayran Label', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-026', 'PLAIN Ayran Label', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-030', 'Mango lassi label', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-031', 'Makhani 250gm Label', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-032', 'Makhani 500g label Back', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-033', 'Makhani 500g label Front', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-034', 'Makhani 1.2 kg label', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-036', 'Case Label Red cherry, 170gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-037', 'Case Label Raspberry, 170gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-038', 'Case Label Mango Lassi', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-040', 'Case Label Mango, 170gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-041', 'Case Label Pineapple, 170gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-042', 'Case Label Strawberry, 170gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-043', 'Case Label Blueberry, 170gm', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-044', '5.5% Balkan 10 kg Label', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LABEL-045', '3.2% Dahi 10 kg Label', 'packaging', 'each', 'Tara Packaging', null, true),
  ('LIDS-001', '2%Probiotic Lids 750gm , (1000pc/box) IPL', 'packaging', 'each', 'IPL Plastic Inc.', null, true),
  ('LIDS-002', '2% Dahi Lids 750gm, (1000pc/box) IPL', 'packaging', 'each', 'IPL', null, true),
  ('LIDS-003', '3.2% Dahi Lids 750gm, (1000pc/box) IPL', 'packaging', 'each', 'IPL', null, true),
  ('LIDS-004', '6%Balkan Lids 750gm, (1000pc/box) Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-005', '2% Halal Yogurt Lids 750 gm, Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-006', '3.2% Halal Yogurt Lids 750 gm, Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-007', '2% Low Fat Dahi Lids 907 gm, Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-008', '4% Whole Milk Dahi Lids 907 gm, Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-009', '4% Organic Yogurt Whole Milk Dahi Lids, 750 gm', 'packaging', 'each', 'Omnia Packaging Inc', null, true),
  ('LIDS-010', '750 gm/500gm Plain lids,630pc/box Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-011', '750 gm/500gm Plain lids,630pc/box IPL', 'packaging', 'each', 'IPL Plastic Inc.', null, true),
  ('LIDS-012', '2% Probiotic Lids 2kg, (6480pc/skid)', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-013', '3.2% Dahi Lids 2kg, ( 6480pc/skid)', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-014', '2% Low Fat Dahi Lids,  2Kg', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-015', '4% Whole Milk Dahi Lids,  2Kg', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-016', 'Plain 2kg Lids, (6480pc/skid)', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-017', 'Plain 3Kg Lids For Ghee', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-018', 'Plain 5Kg Lids For Sour Cream', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-019', '400 gm Ghee Lids, 825pc/box Plasticap', 'packaging', 'each', 'Plasticap', null, true),
  ('LIDS-020', '800 gm Ghee Lids,625pc/box Plasticap', 'packaging', 'each', 'Plasticap', null, true),
  ('LIDS-021', '1.6 kg Ghee Lids Plasticap', 'packaging', 'each', 'Plasticap', null, true),
  ('LIDS-024', 'Plain 2kg Lids for Sour Cream', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-025', 'Plain 5Kg Lids For Sour Cream', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-026', 'Plain 10kg Lids for Sour Cream', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-027', '10kg/12kg Lids, (1400pc/skid plain) Jokey', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-028', '10kg Lids, (124pc/skid plain) IPL', 'packaging', 'each', 'IPL North America Inc.', null, true),
  ('LIDS-029', '16kg Lids, (124pc/skid plain) IPL', 'packaging', 'each', 'IPL North America Inc.', null, true),
  ('LIDS-030', 'Plain Khoa / Makhani  Container Lids Plastipak', 'packaging', 'each', 'Plastipak', null, true),
  ('LIDS-031', '400 gm Ghee Lids, 825pc/box Lanklo', 'packaging', 'each', 'lanklo', null, true),
  ('LIDS-032', '800 gm Ghee Lids,625pc/box Lanklo', 'packaging', 'each', 'lanklo', null, true),
  ('LIDS-033', '1.6 kg Ghee Lids Lanklo', 'packaging', 'each', 'lanklo', null, true),
  ('MILK-001', 'Raw milk - DFO', 'raw', 'L', 'Dairy Farmers of Ontario', null, true),
  ('MILK-002', 'Raw milk - Lactalis', 'raw', 'L', 'Lactalis Canada', null, true),
  ('MILKP-001', 'Skim Milk Powder - Gaylee', 'raw', 'kg', 'Food Tec Canada Inc', null, true),
  ('MILKP-002', 'Skim Milk Power - Lactalis', 'raw', 'kg', 'Lactalis Canada', null, true),
  ('MILKP-003', 'Whole Milk Powder', 'raw', 'kg', 'Lactalis Canada', null, true),
  ('NSEAL-001', '400 gm Ghee neck seal (12234)', 'packaging', 'each', 'U Line', null, true),
  ('NSEAL-002', '800 gm Ghee neck seal (14030)', 'packaging', 'each', 'U Line', null, true),
  ('NSEAL-003', '1.6 kg Ghee neck seal (14972)', 'packaging', 'each', 'U Line', null, true),
  ('PPE-001', 'Hair Net', 'consumable', 'each', 'e & J Supply Inc', null, true),
  ('PPE-002', 'Hand Gloves  Large', 'consumable', 'each', 'e & J Supply Inc', null, true),
  ('PPE-003', 'Hand Gloves MEDIUM', 'consumable', 'each', 'e & J Supply Inc', null, true),
  ('PPE-004', 'Hand Gloves X-Large', 'consumable', 'each', 'e & J Supply Inc', null, true),
  ('PPE-005', 'Shoe Cover', 'consumable', 'each', 'e & J Supply Inc', null, true),
  ('PPE-006', 'Beard Net', 'consumable', 'each', 'e & J Supply Inc', null, true),
  ('PPE-007', 'Cascade Hand paper Rolls', 'consumable', 'each', 'e & J Supply Inc', null, true),
  ('PPE-008', 'Wollen Gloves', 'consumable', 'each', 'e & J Supply Inc', null, true),
  ('TRAY-001', '6 Cup Trays for 750 gm ZEBRA', 'packaging', 'each', 'Zebra Paper Converters Inc.', null, true),
  ('TRAY-002', '4 Tub Trays for 2Kg', 'packaging', 'each', 'Staples Professional', null, true),
  ('TUBS-001', '2% Probiotic Tubs 2kg,( 3240pc/skid)', 'packaging', 'each', 'Plastipak', null, true),
  ('TUBS-002', '3.2% Dahi Tubs 2kg, (3240pc/skid)', 'packaging', 'each', 'Plastipak', null, true),
  ('TUBS-003', 'Plain 2kg Tubs,( 3240pc/skid)', 'packaging', 'each', 'Plastipak', null, true),
  ('TUBS-004', '2% Low Fat Dahi Tubs 2Kg', 'packaging', 'each', 'Plastipak', null, true),
  ('TUBS-005', '4% Whole Milk Dahi Tubs 2Kg', 'packaging', 'each', 'Plastipak', null, true)
on conflict (id) do update
set name = excluded.name,
    type = excluded.type,
    unit = excluded.unit,
    supplier = excluded.supplier,
    low_stock_threshold = coalesce(public.materials.low_stock_threshold, excluded.low_stock_threshold),
    is_active = public.materials.is_active,
    updated_at = now();
